# # name: Deploy
# # on: push
# # jobs:
# #   deploy:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - uses: actions/checkout@v4
# #       - uses: actions/setup-node@v4
# #       - run: npm install
# #       - run: npm run build
# #         env:
# #           VITE_EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
# #           VITE_EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
# #           VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
# #       - uses: peaceiris/actions-gh-pages@v3
# #         with:
# #           github_token: ${{ secrets.GITHUB_TOKEN }}
# #           publish_dir: ./dist
# #       - run: |
# #           echo "=== ENV DUMP ==="
# #           printenv | grep VITE
# #           echo "=== BUILD FILES ==="
# #           grep -r "EMAILJS" dist/ || echo "No vars found in build"

# name: Deploy to GitHub Pages
# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'vite.config.js'
#       - 'src/**'
#       - 'public/**'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0 

#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: npm ci

#       - name: Build with env vars
#         run: npm run build
#         env:
#           VITE_EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
#           VITE_EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
#           VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}

#       - name: Verify build
#         run: |
#           echo "=== Checking built files ==="
#           ls -la dist
#           grep -r "VITE_EMAILJS" dist/ || echo "Not found in build"

#       - name: Deploy to GH Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./dist
#           publish_branch: gh-pages
#           force_orphan: true

name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - run: npm install
      
      - name: Build with env vars
        run: |
          echo "VITE_EMAILJS_USER_ID=${{ secrets.EMAILJS_USER_ID }}" >> .env
          echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.EMAILJS_SERVICE_ID }}" >> .env
          echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.EMAILJS_TEMPLATE_ID }}" >> .env
          cat .env
          npm run build
        env:
          VITE_EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
          
      - name: Debug build output
        run: |
          echo "=== Checking for env vars in build ==="
          grep -r "MISSING_" dist/ && echo "ERROR: Env vars not injected!" || echo "Success: Env vars found"
          
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true