name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
        env:
          VITE_EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - run: |
          echo "=== ENV DUMP ==="
          printenv | grep VITE
          echo "=== BUILD FILES ==="
          grep -r "EMAILJS" dist/ || echo "No vars found in build"